name: Combine PNG and WAV

on:
  workflow_dispatch:
    inputs:
      input_zip_link:
        description: "Input ZIP file link"
        required: false
        type: string
        default: https://drive.google.com/file/d/1tDZx6Ct-dkIqJ_a7pk3-jbrnCvjr2OG7/view?usp=sharing

jobs:
  combine-png-wav:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
    #   - name: Checkout Repository
    #     uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip python3-dev build-essential libjpeg-dev zlib1g-dev libjpeg8-dev libfreetype6-dev ffmpeg imagemagick && pip3 install pandas openpyxl moviepy pillow gdown

      - name: Download Input File
        run: | 
          gdown --id 1J-QWKNEn7-WQUlDGnFfl-ryNAA0Ifpcj
          unzip PNG+WAV.zip
          ls
          rm PNG+WAV.zip 

      - name: Extract File ID from Input Link
        id: extract_id
        run: |
          echo "Input Google Drive link: ${{ github.event.inputs.input_zip_link }}"
          
          # Extract the file ID using regex
          if [[ "${{ github.event.inputs.input_zip_link }}" =~ /d/([a-zA-Z0-9_-]{33,}) ]]; then
            file_id="${BASH_REMATCH[1]}"
            echo "File ID extracted: $file_id"
            echo "file_id=$file_id" >> $GITHUB_ENV
          else
            echo "Error: Invalid Google Drive link provided."
            exit 1
          fi

      # Step 2: Download input.zip using the provided link
      - name: Download Input File
        run: |
          cd Video.tmp
          gdown --id ${{ env.file_id }}
          unzip input.zip

      # Step 3: Unzip the downloaded file
      - name: Combine Clips
        run: |
          cd App
          python3 App_ffmpeg_raw.py

    #   # Step 4: Install Python and dependencies
    #   - name: Set up Python environment
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.x'

    #   - name: Install Dependencies
    #     run: |
    #       pip install -r requirements.txt

    #   # Step 5: Execute the Python script
    #   - name: Combine PNG and WAV
    #     run: |
    #       python combine.py input_files output

    #   # Step 6: Archive the output folder
    #   - name: Archive Output
    #     run: |
    #       zip -r output.zip output

    #   # Step 7: Upload the output as an artifact
    #   - name: Upload Artifact
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: combined-clips
    #       path: output.zip