name: Extract Google Drive File ID

on:
  workflow_dispatch:
    inputs:
      gdrive_link:
        description: "Google Drive link"
        required: true
        type: string

jobs:
  extract-file-id:
    runs-on: ubuntu-latest

    steps:
      - name: Extract File ID from Input Link
        id: extract_id
        run: |
          echo "Input Google Drive link: ${{ github.event.inputs.gdrive_link }}"
          
          # Extract the file ID using regex
          if [[ "${{ github.event.inputs.gdrive_link }}" =~ /d/([a-zA-Z0-9_-]{33,}) ]]; then
            file_id="${BASH_REMATCH[1]}"
            echo "File ID extracted: $file_id"
            echo "file_id=$file_id" >> $GITHUB_ENV
          else
            echo "Error: Invalid Google Drive link provided."
            exit 1
          fi

      - name: Output Extracted File ID
        run: |
          echo "The extracted file ID is: ${{ steps.extract_id.outputs.file_id }}"