name: Combine and Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  combine_and_upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials to file using PowerShell
        shell: pwsh
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.GOOGLE_CREDENTIALS_B64 }}")) | Out-File -FilePath credentials.json -Encoding utf8

      - name: Run combine and upload script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: |
          python combine_upload.py