name: Combine JPG and MP3 to MP4

on:
  workflow_dispatch:
    inputs:
      jpg_file:
        description: 'Path to the JPG file'
        required: true
        default: 'input.jpg'
      mp3_file:
        description: 'Path to the MP3 file'
        required: true
        default: 'input.mp3'
      output_file:
        description: 'Path to the output MP4 file'
        required: true
        default: 'output.mp4'

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Run combine script
        run: |
          python combine.py "${{ github.event.inputs.jpg_file }}" "${{ github.event.inputs.mp3_file }}" "${{ github.event.inputs.output_file }}"

      - name: Upload MP4 as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined_video
          path: ${{ github.event.inputs.output_file }}