name: Combine JPG and MP3 to MP4 with Google Drive User Auth

on:
  workflow_dispatch:
    inputs:
      jpg_file_id:
        description: 'Google Drive File ID for the JPG'
        required: true
      mp3_file_id:
        description: 'Google Drive File ID for the MP3'
        required: true
      output_folder_id:
        description: 'Google Drive Folder ID for the output MP4'
        required: true

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload client_id.json
        env:
          CLIENT_ID_JSON: ${{ secrets.CLIENT_ID_JSON }}
        run: |
          echo "${CLIENT_ID_JSON}" > client_id.json

      - name: Run combine script
        env:
          JPG_FILE_ID: ${{ github.event.inputs.jpg_file_id }}
          MP3_FILE_ID: ${{ github.event.inputs.mp3_file_id }}
          OUTPUT_FOLDER_ID: ${{ github.event.inputs.output_folder_id }}
        run: python combine_with_user_auth.py