name: JPG and MP3 to MP4 Conversion from Google Drive

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment and install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client google-drive-downloader

    - name: Configure Google OAuth credentials
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: |
        echo '{
            "installed": {
                "client_id": "'$GOOGLE_CLIENT_ID'",
                "client_secret": "'$GOOGLE_CLIENT_SECRET'",
                "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"],
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token"
            }
        }' > credentials.json

    - name: Authenticate and Download JPG/MP3 files from Google Drive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      run: |
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaIoBaseDownload
        import io

        # Define file IDs for download
        files_to_download = {
            "input.jpg": "14HX7c21qgJZuVXbIgXlJSMme5DtyZuAc",
            "input.mp3": "1hvIgXoXxqiu3cPCl01oiSP24S6S1HJNI"
        }

        # Authenticate and initialize Drive API client
        service = build('drive', 'v3', credentials=GOOGLE_APPLICATION_CREDENTIALS)

        # Download each file
        for file_name, file_id in files_to_download.items():
            request = service.files().get_media(fileId=file_id)
            file_io = io.FileIO(file_name, 'wb')
            downloader = MediaIoBaseDownload(file_io, request)
            done = False
            while not done:
                status, done = downloader.next_chunk()

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Combine JPG and MP3 to create MP4
      run: ffmpeg -loop 1 -i input.jpg -i input.mp3 -c:v libx264 -c:a aac -shortest output.mp4

    - name: Upload MP4 to Google Drive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      run: |
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        # Authenticate and initialize Drive API client
        service = build('drive', 'v3', credentials=GOOGLE_APPLICATION_CREDENTIALS)

        # Upload the output.mp4 to the specified folder
        file_metadata = {
            'name': 'output.mp4',
            'mimeType': 'video/mp4',
            'parents': ['1dlnublR0oSB-AszlYfBtq_CKseffIZvm']  # Destination folder ID
        }
        media = MediaFileUpload('output.mp4', mimetype='video/mp4')
        service.files().create(body=file_metadata, media_body=media, fields='id').execute()